variable "aws_region" {}
variable "email" {}
variable "environment" {}
variable "application" {}
variable "jira_ticket_no" {}
variable "user_name" {}
variable "max_instance_size" {}
variable "min_instance_size" {}
variable "desired_instance_size" {}
